from datetime import datetime
from sys import argv
from os.path import join
import json

import settings
from league import League
from tournaments import get_tournament_from_url
from template import generate_static_html


# split a .txt file into a list of lines
def get_lines(file_name):
    file = open(file_name, "r")
    text = file.read()
    file.close()

    return [l for l in text.split("\n") if l]


# splits alts into a list of tuples
def get_alts(file_name):
    alts = {}

    for line in get_lines(file_name):
        if line:
            # League.get_check_str removes punctuation and spaces / capitalizes
            names = [League.get_check_str(n) for n in line.split(" ")]
            for n in names[1:]:
                alts[n] = names[0]

    return alts


# returns a League object generated by the .json file or
# a new object if the file is not found
def get_league(file_name):
    try:
        file = open(join("json", file_name))
        json_data = json.load(file)
        file.close()

        return League.get_from_json(json_data)

    except FileNotFoundError:
        return League(settings.LEAGUE_NAME)


# outputs a list of tuples with a url and strength argument
# for use by the Tournament.get_tournament_by_url function
def get_tourney_args(file_name):
    tourneys = []

    for line in get_lines(file_name):
        if " " in line:
            line = line.split(" ")
            url = line[0]
            strength = float(line[1])
        else:
            url = line
            strength = 1

        tourneys.append(
            (url, strength)
        )

    return tourneys


# generates matches from tournaments and applies season elo
# to League object
def get_rankings(league, tourney_file, alts, follow):
    args = []

    # checks against existing tourneys in League object
    for a in get_tourney_args(tourney_file):
        url, strength = a

        if not league.check_tourney_url(url):
            args.append(a)

    # get_tournament_from_url(url, strength, alts)
    tourneys = [
        get_tournament_from_url(a[0], a[1], alts=alts) for a in args
    ]

    for t in tourneys:
        league.add_tournament(t, player_list=follow)

    league.apply_season_elo()


# generates static html file with css stylesheet.
# provisional_games defines game count for "provisional_player" css class
def save_html(league, file_name, css_file, provisional_games):
    file_name = file_name.replace(".json", ".html")
    html = open(join("html", file_name), "w")
    html.write(generate_static_html(
        league.get_json_data(), css_file,
        provisional_games
    ))


# save League object as .json file
def save_json(league, file_name):
    file = open(join("json", file_name), "w")
    json.dump(league.get_json_data(), file, indent=4)
    file.close()


# Script parameters:
#   *.css   - specify stylesheet file name
#   *.json  - specify json file name
#   *.html  - specify html file name
#   html    - force html file creation
#   follow  - apply player_list arg tournament.get_matches
#   f       - force all match elo changes to be applied from scratch
#   save    - force json data to be saved

if __name__ == "__main__":
    style_sheet = settings.CSS_FILE
    league_name = settings.LEAGUE_NAME
    league_alts = get_alts(settings.ALTS_FILE)

    league_file = None
    player_list = None
    html_file = None

    force_reset = False
    save_league = False

    # scan script parameters
    for arg in argv:
        if ".css" in arg:
            style_sheet = arg

        if ".json" in arg:
            league_file = arg

        if ".html" in arg:
            html_file = arg

        if arg == "follow":
            player_list = get_lines(settings.FOLLOW_FILE)

        if arg == "save":
            save_league = True
            if not league_file:
                time = datetime.now().isoformat().replace(":", "")
                league_file = league_name.replace(" ", "_") + time + ".json"

        if arg == "html":
            html_file = True

        if arg == "f":
            force_reset = True

    # create League object
    if league_file and not force_reset:
        league_obj = get_league(league_file)
    else:
        league_obj = League(settings.LEAGUE_NAME)

    # generate elo ratings
    get_rankings(
        league_obj, settings.TOURNEY_FILE,
        league_alts,
        follow=player_list
    )

    # generate html
    if html_file:
        if html_file is True:
            time = datetime.now().isoformat().replace(":", "")
            html_file = league_obj.name + time + ".html"

        save_html(
            league_obj, html_file, style_sheet,
            settings.PROVISIONAL_GAMES
        )

    # save json data
    if save_league:
        save_json(league_obj, league_file)
