# DEFINE THESE VALUES THEN CHANGE FILE_NAME TO "settings.py"

# SETTINGS

LEAGUE_NAME = "Your League"
TOURNEY_FILE = "tournaments.txt"
ALTS_FILE = "alts.txt"
FOLLOW_FILE = "follow.txt"
CSS_FILE = "style.css"
PROVISIONAL_GAMES = 20

# ELO
START_ELO = 1500
ELO_WIDTH = 400
K_FACTOR = 32

# CHALLONGE
CHALLONGE_USERNAME = "userName"
CHALLONGE_API_KEY = "apiKey"
